import localFont from "next/font/local";
import "./globals.css";
import { Navbar, Footer } from "@/component";
import Script from "next/script";
import { ThemeProviderWrapper } from "@/component/ThemeProviderWrapper";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Cryptoket",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProviderWrapper>
          <Navbar />
          {children}
          <Footer />
        </ThemeProviderWrapper>
        <Script
          src="https://kit.fontawesome.com/9c0219f7b9.js"
          crossOrigin="anonymous"
          async
        />
      </body>
    </html>
  );
}
